export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const BLOGS_FETCH_SUCCESS = "BLOGS_FETCH_SUCCESS";
export const BLOGS_FETCH_ERROR = "BLOGS_FETCH_ERROR";
export const USERS_FETCH_SUCCESS = "USERS_FETCH_SUCCESS";
export const USERS_FETCH_ERROR = "USERS_FETCH_ERROR";

